## Variables
@boardId = 1


# security 구현 완료 시 헤더에 토큰 추가

### 보드 생성
POST http://localhost:8080/boards
Content-Type: application/json
Authorization: {{Authorization}}

{
  "name":"보드 제목",
  "introduction":"한줄소개"
}

### 보드 수정
PUT http://localhost:8080/boards/{{boardId}}
Content-Type: application/json
Authorization: {{Authorization}}

{
  "name":"보드 제목 수정2",
  "introduction":"한줄 소개 수정2"
}

### 보드삭제
DELETE http://localhost:8080/boards/4
Content-Type: application/json
Authorization: {{Authorization}}



### 보드 전체 목록 조회
GET http://localhost:8080/boards
Authorization: {{Authorization}}

{
  "name":"보드 제목 수정",
  "introduction":"한줄 소개 수정"
}

### 보드 선택 조회
GET http://localhost:8080/boards/2
Authorization: {{Authorization}}

### 보드 초대
POST http://localhost:8080/boards/2/invite/3
Content-Type: application/json
Authorization: {{Authorization}}