## Variables
@columnId = 1
@cardId = 1

### 카드 생성
POST http://localhost:8080/column/{{columnId}}/cards
Content-Type: application/json

{
  "title":"카드 제목",
  "content":"카드 내용",
  "responsiblePerson":"담당자",
  "deadline":"2024-07-10T21:36"
}

### 카드 수정
PUT http://localhost:8080/column/{{columnId}}/cards/{{cardId}}
Content-Type: application/json

{
  "title":"카드 제목 수정",
  "content":"카드 내용 수정",
  "responsiblePerson":"담당자 수정",
  "deadline":"2024-07-11T10:28"
}