## Variables
@boardId = 2
@columnId = 1
@cardId = 1

# security 구현 완료 시 헤더에 토큰 추가
#accessToken: {{accessToken}}
#refreshToken: {{refreshToken}}

### 카드 생성
POST http://localhost:8080/columns/{{columnId}}/cards
Content-Type: application/json
Authorization: {{Authorization}}

{
  "title":"카드 제목",
  "content":"카드 내용",
  "responsiblePerson":"담당자",
  "deadline":"2024-07-10T21:36"
}

### 카드 수정
PUT http://localhost:8080/cards/{{cardId}}
Content-Type: application/json
Authorization: {{Authorization}}

{
  "title":"카드 제목 수정",
  "content":"카드 내용 수정",
  "responsiblePerson":"담당자 수정",
  "deadline":"2024-07-11T10:28"
}

### 카드 삭제
DELETE http://localhost:8080/cards/{{cardId}}
Authorization: {{Authorization}}

### 카드 단일 조회 (RestAPI)
GET http://localhost:8080/api/cards/{{cardId}}

### 보드 전체 카드 목록 조회
GET http://localhost:8080/boards/{{boardId}}/cards

### 컬럼 별 카드 목록 조회
GET http://localhost:8080/columns/{{columnId}}/cards

### 전체 컬럼 카드 목록 조회
GET http://localhost:8080/boards/{{boardId}}/cards/byColumns

### 사용자 별 카드 목록 조회
GET http://localhost:8080/boards/{{boardId}}/cards/byUser
