### 유저 찾기
GET http://localhost:8080/users
Content-Type: application/json
Authorization: {{Authorization}}
RefreshToekn: {{RefreshToken}}

{
  "email": "test1234@gmail.com"
}

### 유저 찾기 fail case(user1로 로그인시)
GET http://localhost:8080/users
Content-Type: application/json
Authorization: {{Authorization}}
RefreshToekn: {{RefreshToken}}

{
  "email": "user11111@gmail.com"
}