### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "accountId": "test1234",
  "password": "test1234!!"
}

> {%
 client.global.set("Authorization", response.headers.valueOf("Authorization"));
 client.log("Authorization: " + response.headers.valueOf("Authorization"));

 client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
 client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));

 %}

### 로그아웃
POST http://localhost:8080/users/logout
Authorization: {{Authorization}}
RefreshToekn: {{RefreshToken}}


> {%
    client.global.clear("Authorization");
    client.global.clear("RefreshToken");

%}