### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "accountId": "test1",
  "password": "test123!"
}

> {%
 client.global.set("Authorization", response.headers.valueOf("Authorization"));
 client.log("Authorization: " + response.headers.valueOf("Authorization"));

 client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
 client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
 %}

### 로그아웃
POST http://localhost:8080/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MSIsImF1dGgiOiJNQU5BR0VSIiwiZXhwIjoxNzIxMDE0MzI5LCJpYXQiOjE3MjEwMTA3Mjl9.KhA23TM_n1v44aPej_wkgo8XdxjtRIb9JfTZ5H_Msu0
RefreshToken: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MSIsImF1dGgiOiJNQU5BR0VSIiwiZXhwIjoxNzIyMjIwMzI5LCJpYXQiOjE3MjEwMTA3Mjl9.2cq1__7k4CxO6vWMyi1aZjjVo0V7NMlLMVtrYMEknTM


> {%
    client.global.clear("Authorization");
    client.global.clear("RefreshToken");
%}