### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "password": "{{password}}"
}

> {%
 client.global.set("Authorization", response.headers.valueOf("Authorization"));
 client.log("Authorization: " + response.headers.valueOf("Authorization"));

 client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
 client.log("RefreshToken: " + response.headers.valueOf("RefreshToken"));
 %}